# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('latlng', models.CharField(max_length=128)),
            ],
        ),
    ]
